name: Installing Python 
on: [push]

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python 
        uses: actions/setup-python@v2
        with: 
          python-version: 3.7
      - run: python --version
